### ISSUE TITLE
Some documentation

### ISSUE THREAD

**Issue by Tarrke** [amitkan1995/Face-Reck#1]
Hi,

your project seems really interesting, and I'd like to test this, maybe even at work. Could you provide, even light, documentation on how to run this on a new set of data?

Thanks a lot!

**Comment by Tarrke** [comment]
For example I did try to install your project. Here is my pip freeze result :
cx-Freeze==5.1.1
numpy==1.14.5
opencv-python==3.4.1.15
pandas==0.23.1
Pillow==5.2.0
python-dateutil==2.7.3
pytz==2018.5
six==1.11.0

The tkinter interface runs well, but when I try to hit the 'Train Images' or 'Track Images' buttons :
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "train.py", line 94, in TrainImages
    recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face'

Ok found the problem... Here is my pip freeze result:
cx-Freeze==5.1.1
numpy==1.14.5
opencv-contrib-python==3.4.1.15
opencv-python==3.4.1.15
pandas==0.23.1
Pillow==5.2.0
python-dateutil==2.7.3
pytz==2018.5
six==1.11.0
